# Generated by Django 4.2.16 on 2024-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FLIGHT",
            fields=[
                ("flt_id", models.AutoField(primary_key=True, serialize=False)),
                ("flt_name", models.CharField(max_length=20)),
                ("flt_from", models.CharField(max_length=20)),
                ("flt_to", models.CharField(max_length=20)),
                ("flt_duration", models.IntegerField()),
            ],
        ),
    ]
